workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 15
    environment:
      node: 18.16.0
    scripts:
      - name: Install Node dependencies
        script: npm install
      - name: Build web app
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync android
      - name: Fix Gradle permissions
        script: chmod +x android/gradlew
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
