workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 15
    environment:
      vars:
        PACKAGE_NAME: "com.example.appinsight"
      node: 18.16.0
      android_signing:
        - debug
    scripts:
      - name: Install Node dependencies
        script: npm install
      - name: Build web app
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync android
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
